version: "3"

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
  app:
    image: order-management-img
    depends_on:
      - mongodb
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb/order-management
